# Generated by Django 3.1.7 on 2022-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pwd',
            field=models.CharField(default=12, max_length=155),
            preserve_default=False,
        ),
    ]
